config/routes.rb
Rails.application.routes.draw do
  root 'lives#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :lives
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/live.rb
class Live < ApplicationRecord
  validates :subject, presence: true
  
  belongs_to :author, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable 
         # :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/lives_controller.rb
class LivesController < ApplicationController
  before_action :set_live, only: [:show, :edit, :update, :destroy]

  # GET /lives
  def index
    @lives = Live.all
  end

  # GET /lives/1
  def show
  end

  # GET /lives/new
  def new
    @live = Live.new
  end

  # GET /lives/1/edit
  def edit
    if @live.author != current_user
      redirect_to lives_path, alert: 'Você não tem permissão para editar essa live'
    end
  end

  # POST /lives
  def create
    @live = Live.new(live_params.merge(author: current_user))

    if @live.save
      redirect_to @live, notice: 'Live was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /lives/1
  def update
    if @live.update(live_params)
      redirect_to @live, notice: 'Live was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /lives/1
  def destroy
    @live.destroy
    redirect_to lives_url, notice: 'Live was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_live
      @live = Live.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def live_params
      params.require(:live).permit(:subject, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Easy Lives</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <% if user_signed_in? %>
      <nav>
        Logado como <strong><%= current_user.name  %></strong>
        - 
        <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
      </nav>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/lives/_form.html.erb
<%= form_with(model: live, local: true) do |form| %>
  <% if live.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(live.errors.count, "error") %> prohibited this live from being saved:</h2>

      <ul>
      <% live.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject, 'Assunto' %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :description, 'Descrição' %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lives/edit.html.erb
<h1>Editing live</h1>

<%= render 'form', live: @live %>

<%= link_to 'Show', @live %> |
<%= link_to 'Back', lives_path %>

app/views/lives/index.html.erb
<h1>Lives</h1>

<table>
  <thead>
    <tr>
      <th>Assunto</th>
      <th>Descrição</th>
      <th>Autor</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lives.each do |live| %>
      <tr>
        <td><%= link_to live.subject, live %></td>
        <td><%= live.description %></td>
        <td><%= live.author.name %></td>

        <% if live.author == current_user  %>
          <td><%= link_to 'Edit', edit_live_path(live) %></td>
        <% end  %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Sugerir live', new_live_path %>

app/views/lives/new.html.erb
<h1>Sugerir live</h1>

<%= render 'form', live: @live %>
<%= link_to 'Voltar', lives_path %>

app/views/lives/show.html.erb
<p>
  <strong>Assunto:</strong>
  <%= @live.subject %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @live.description %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @live.author.name %>
</p>

<% if @live.author == current_user  %>
  <%= link_to 'Editar', edit_live_path(@live) %> |
<% end  %>

<%= link_to 'Voltar', lives_path %>